# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'curver/ui/curve_edit.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_curveEditWindow(object):
    def setupUi(self, curveEditWindow):
        curveEditWindow.setObjectName("curveEditWindow")
        curveEditWindow.resize(383, 500)
        self.vectorMoveButton = QtWidgets.QPushButton(curveEditWindow)
        self.vectorMoveButton.setGeometry(QtCore.QRect(10, 130, 121, 32))
        self.vectorMoveButton.setObjectName("vectorMoveButton")
        self.doneButton = QtWidgets.QPushButton(curveEditWindow)
        self.doneButton.setGeometry(QtCore.QRect(250, 460, 113, 32))
        self.doneButton.setObjectName("doneButton")
        self.curveName = QtWidgets.QLineEdit(curveEditWindow)
        self.curveName.setEnabled(True)
        self.curveName.setGeometry(QtCore.QRect(30, 10, 321, 31))
        self.curveName.setObjectName("curveName")
        self.vectorMoveBox = QtWidgets.QGroupBox(curveEditWindow)
        self.vectorMoveBox.setGeometry(QtCore.QRect(130, 120, 221, 41))
        self.vectorMoveBox.setTitle("")
        self.vectorMoveBox.setFlat(True)
        self.vectorMoveBox.setObjectName("vectorMoveBox")
        self.xPos = QtWidgets.QLineEdit(self.vectorMoveBox)
        self.xPos.setGeometry(QtCore.QRect(0, 10, 40, 30))
        self.xPos.setInputMethodHints(QtCore.Qt.ImhNone)
        self.xPos.setObjectName("xPos")
        self.yPos = QtWidgets.QLineEdit(self.vectorMoveBox)
        self.yPos.setGeometry(QtCore.QRect(60, 10, 40, 30))
        self.yPos.setInputMethodHints(QtCore.Qt.ImhNone)
        self.yPos.setObjectName("yPos")
        self.moveButton = QtWidgets.QPushButton(self.vectorMoveBox)
        self.moveButton.setGeometry(QtCore.QRect(110, 10, 113, 32))
        self.moveButton.setObjectName("moveButton")
        self.cancelButton = QtWidgets.QPushButton(curveEditWindow)
        self.cancelButton.setGeometry(QtCore.QRect(250, 420, 113, 32))
        self.cancelButton.setObjectName("cancelButton")
        self.permutePointsButton = QtWidgets.QPushButton(curveEditWindow)
        self.permutePointsButton.setGeometry(QtCore.QRect(10, 170, 121, 32))
        self.permutePointsButton.setObjectName("permutePointsButton")
        self.rotateCurveButton = QtWidgets.QPushButton(curveEditWindow)
        self.rotateCurveButton.setGeometry(QtCore.QRect(10, 250, 121, 32))
        self.rotateCurveButton.setObjectName("rotateCurveButton")
        self.rotateCurveBox = QtWidgets.QGroupBox(curveEditWindow)
        self.rotateCurveBox.setGeometry(QtCore.QRect(130, 220, 251, 61))
        self.rotateCurveBox.setTitle("")
        self.rotateCurveBox.setObjectName("rotateCurveBox")
        self.rotateDoneButton = QtWidgets.QPushButton(self.rotateCurveBox)
        self.rotateDoneButton.setGeometry(QtCore.QRect(160, 30, 71, 32))
        self.rotateDoneButton.setObjectName("rotateDoneButton")
        self.rotationSlider = QtWidgets.QSlider(self.rotateCurveBox)
        self.rotationSlider.setGeometry(QtCore.QRect(0, 30, 160, 22))
        self.rotationSlider.setOrientation(QtCore.Qt.Horizontal)
        self.rotationSlider.setObjectName("rotationSlider")
        self.scaleCurveButton = QtWidgets.QPushButton(curveEditWindow)
        self.scaleCurveButton.setGeometry(QtCore.QRect(10, 290, 121, 32))
        self.scaleCurveButton.setObjectName("scaleCurveButton")
        self.deletePointButton = QtWidgets.QPushButton(curveEditWindow)
        self.deletePointButton.setGeometry(QtCore.QRect(10, 90, 121, 32))
        self.deletePointButton.setObjectName("deletePointButton")
        self.addPointButton = QtWidgets.QPushButton(curveEditWindow)
        self.addPointButton.setGeometry(QtCore.QRect(10, 50, 121, 32))
        self.addPointButton.setObjectName("addPointButton")
        self.exportCurveButton = QtWidgets.QPushButton(curveEditWindow)
        self.exportCurveButton.setGeometry(QtCore.QRect(10, 330, 121, 32))
        self.exportCurveButton.setObjectName("exportCurveButton")
        self.undoButton = QtWidgets.QPushButton(curveEditWindow)
        self.undoButton.setGeometry(QtCore.QRect(10, 460, 121, 32))
        self.undoButton.setObjectName("undoButton")
        self.reverseCurveButton = QtWidgets.QPushButton(curveEditWindow)
        self.reverseCurveButton.setGeometry(QtCore.QRect(10, 210, 121, 32))
        self.reverseCurveButton.setObjectName("reverseCurveButton")
        self.scaleCurveBox = QtWidgets.QGroupBox(curveEditWindow)
        self.scaleCurveBox.setGeometry(QtCore.QRect(130, 280, 251, 61))
        self.scaleCurveBox.setTitle("")
        self.scaleCurveBox.setObjectName("scaleCurveBox")
        self.scaleDoneButton = QtWidgets.QPushButton(self.scaleCurveBox)
        self.scaleDoneButton.setGeometry(QtCore.QRect(160, 30, 71, 32))
        self.scaleDoneButton.setObjectName("scaleDoneButton")
        self.scaleSlider = QtWidgets.QSlider(self.scaleCurveBox)
        self.scaleSlider.setGeometry(QtCore.QRect(0, 30, 160, 22))
        self.scaleSlider.setSliderPosition(50)
        self.scaleSlider.setOrientation(QtCore.Qt.Horizontal)
        self.scaleSlider.setObjectName("scaleSlider")
        self.addPointBox = QtWidgets.QGroupBox(curveEditWindow)
        self.addPointBox.setGeometry(QtCore.QRect(130, 40, 221, 41))
        self.addPointBox.setTitle("")
        self.addPointBox.setFlat(True)
        self.addPointBox.setObjectName("addPointBox")
        self.addXPos = QtWidgets.QLineEdit(self.addPointBox)
        self.addXPos.setGeometry(QtCore.QRect(0, 10, 40, 30))
        self.addXPos.setInputMethodHints(QtCore.Qt.ImhNone)
        self.addXPos.setObjectName("addXPos")
        self.addYPos = QtWidgets.QLineEdit(self.addPointBox)
        self.addYPos.setGeometry(QtCore.QRect(60, 10, 40, 30))
        self.addYPos.setInputMethodHints(QtCore.Qt.ImhNone)
        self.addYPos.setObjectName("addYPos")
        self.addButton = QtWidgets.QPushButton(self.addPointBox)
        self.addButton.setGeometry(QtCore.QRect(110, 10, 113, 32))
        self.addButton.setObjectName("addButton")
        self.joinSplitButton = QtWidgets.QPushButton(curveEditWindow)
        self.joinSplitButton.setGeometry(QtCore.QRect(10, 410, 121, 32))
        self.joinSplitButton.setObjectName("joinSplitButton")
        self.weightBox = QtWidgets.QGroupBox(curveEditWindow)
        self.weightBox.setGeometry(QtCore.QRect(130, 70, 101, 41))
        self.weightBox.setTitle("")
        self.weightBox.setFlat(True)
        self.weightBox.setObjectName("weightBox")
        self.weightVal = QtWidgets.QLineEdit(self.weightBox)
        self.weightVal.setGeometry(QtCore.QRect(60, 10, 40, 30))
        self.weightVal.setInputMethodHints(QtCore.Qt.ImhNone)
        self.weightVal.setObjectName("weightVal")
        self.weightLabel = QtWidgets.QLabel(self.weightBox)
        self.weightLabel.setGeometry(QtCore.QRect(10, 20, 60, 16))
        self.weightLabel.setObjectName("weightLabel")
        self.editWeightBox = QtWidgets.QGroupBox(curveEditWindow)
        self.editWeightBox.setGeometry(QtCore.QRect(20, 370, 230, 40))
        self.editWeightBox.setTitle("")
        self.editWeightBox.setFlat(True)
        self.editWeightBox.setObjectName("editWeightBox")
        self.editWeightButton = QtWidgets.QPushButton(self.editWeightBox)
        self.editWeightButton.setGeometry(QtCore.QRect(-10, 0, 121, 32))
        self.editWeightButton.setObjectName("editWeightButton")
        self.editWeightValBox = QtWidgets.QGroupBox(self.editWeightBox)
        self.editWeightValBox.setGeometry(QtCore.QRect(120, -10, 101, 41))
        self.editWeightValBox.setTitle("")
        self.editWeightValBox.setFlat(True)
        self.editWeightValBox.setObjectName("editWeightValBox")
        self.editWeightVal = QtWidgets.QLineEdit(self.editWeightValBox)
        self.editWeightVal.setGeometry(QtCore.QRect(60, 10, 40, 30))
        self.editWeightVal.setInputMethodHints(QtCore.Qt.ImhNone)
        self.editWeightVal.setObjectName("editWeightVal")
        self.editWeightLabel = QtWidgets.QLabel(self.editWeightValBox)
        self.editWeightLabel.setGeometry(QtCore.QRect(10, 20, 60, 16))
        self.editWeightLabel.setObjectName("editWeightLabel")

        self.retranslateUi(curveEditWindow)
        QtCore.QMetaObject.connectSlotsByName(curveEditWindow)

    def retranslateUi(self, curveEditWindow):
        _translate = QtCore.QCoreApplication.translate
        curveEditWindow.setWindowTitle(_translate("curveEditWindow", "Form"))
        self.vectorMoveButton.setText(_translate("curveEditWindow", "Move by vector"))
        self.doneButton.setText(_translate("curveEditWindow", "Done"))
        self.moveButton.setText(_translate("curveEditWindow", "Move"))
        self.cancelButton.setText(_translate("curveEditWindow", "Cancel"))
        self.permutePointsButton.setText(_translate("curveEditWindow", "Permute points"))
        self.rotateCurveButton.setText(_translate("curveEditWindow", "Rotate by angle"))
        self.rotateDoneButton.setText(_translate("curveEditWindow", "Done"))
        self.scaleCurveButton.setText(_translate("curveEditWindow", "Scale"))
        self.deletePointButton.setText(_translate("curveEditWindow", "Delete point"))
        self.addPointButton.setText(_translate("curveEditWindow", "Add point"))
        self.exportCurveButton.setText(_translate("curveEditWindow", "Export"))
        self.undoButton.setText(_translate("curveEditWindow", "Undo"))
        self.reverseCurveButton.setText(_translate("curveEditWindow", "Reverse points"))
        self.scaleDoneButton.setText(_translate("curveEditWindow", "Done"))
        self.addButton.setText(_translate("curveEditWindow", "Add"))
        self.joinSplitButton.setText(_translate("curveEditWindow", "Join / Split"))
        self.weightLabel.setText(_translate("curveEditWindow", "weight:"))
        self.editWeightButton.setText(_translate("curveEditWindow", "Edit Weight"))
        self.editWeightLabel.setText(_translate("curveEditWindow", "weight:"))
